version: 2.1

orbs:
  snyk: snyk/snyk@2.3.3

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20
    environment:
      AWS_REGION: us-east-1

jobs:
  snyk_scan:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Python, pip, jq, and unzip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip jq unzip

      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
            rm -rf awscliv2.zip aws
            aws --version

      - run:
          name: Assume AWS OIDC Role
          command: |
            ROLE_ARN="arn:aws:iam::961341535277:role/newcircleci"
            if [ -z "$CIRCLE_OIDC_TOKEN" ]; then
              echo "OIDC token not found! Did you attach the correct Context with OIDC enabled?" && exit 1
            fi
            OIDC_TOKEN="$CIRCLE_OIDC_TOKEN"
            CREDS_JSON=$(aws sts assume-role-with-web-identity \
              --role-arn "$ROLE_ARN" \
              --role-session-name "newcircleci" \
              --web-identity-token "$OIDC_TOKEN" \
              --region $AWS_REGION)
            export AWS_ACCESS_KEY_ID=$(echo "$CREDS_JSON" | jq -r '.Credentials.AccessKeyId')
            export AWS_SECRET_ACCESS_KEY=$(echo "$CREDS_JSON" | jq -r '.Credentials.SecretAccessKey')
            export AWS_SESSION_TOKEN=$(echo "$CREDS_JSON" | jq -r '.Credentials.SessionToken')
            echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $BASH_ENV

      - run:
          name: Install Python dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip3 install -r requirements.txt
            fi

      - run:
          name: Fetch snyk API token from Secrets Manager
          command: |
            SECRET_JSON=$(aws secretsmanager get-secret-value \
              --region $AWS_REGION \
              --secret-id newcircleci/snyk/api-token \
              --query SecretString \
              --output text)
            SNYK_TOKEN=$(echo $SECRET_JSON | jq -r '."newcircleci/snyk/api-token"')
            echo "export SNYK_TOKEN=$SNYK_TOKEN" >> $BASH_ENV

  security-scan:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      # Dependency scan (requirements.txt)
      - snyk/scan:
          monitor: true
          severity-threshold: low
          fail-on-issues: true
          target-file: requirements.txt
      # Code scan (Snyk Code scans .py files)
      - snyk/scan:
          monitor: true
          severity-threshold: low
          fail-on-issues: true
          project-type: code

workflows:
  snyk_security_scan:
    jobs:
      - snyk_scan
      - security-scan
