version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20

jobs:
  snyk_scan: 
    executor: node-executor
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Fetch snyk API token from Secrets Manager
          command: |
            export SNYK_TOKEN=$(aws secretsmanager get-secret-value --secret-id ci/snyk/api-token --query SecretString --output text)
            echo "export SNYK_TOKEN=$SNYK_TOKEN" >> $BASH_ENV
      - run:
          name: Install snyk CLI
          command: npm install -g snyk
      - run:
          name: Run snyk test
          command: snyk test

workflows:
  snyk_security_scan:
    jobs:
      - snyk_scan